modLoader = "javafml"
loaderVersion = "[4,)"
license = "MPL-2.0"

[[mods]]
modId = "communitytiertagger"
displayName = "CommunityTierTagger"
version = "${version}"

iconFile = "assets/communitytiertagger/icon.png"
authors = "uku, netiyiy (original creator), Evantiisx"
description = "Display player's PvP tiers from any CommunityTierTagger-compatible community in their nametag!"
displayURL = "https://modrinth.com/project/YOUR-MODRINTH-ID"

[[dependencies.communitytiertagger]]
modId = "minecraft"
type = "required"
versionRange = "[26.3,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.communitytiertagger]]
modId = "neoforge"
type = "required"
versionRange = "[26.3.0.0-beta,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.communitytiertagger]]
modId = "ukulib"
type = "required"
versionRange = "[2.2.0,3)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "CommunityTierTagger.mixins.json"
